[package]
name = "segmentor"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
clap = { version = "4.3.21", features = ["derive"] }
rand = "0.8.5"
bincode = "1.3.3"
anyhow = "1.0.86"
risc0-zkvm = { version = "1.1.2", features = ["prove"] }